export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const ADDING_ACTIVITY_SUCCESS = 'ADDING_ACTIVITY_SUCCESS';
export const ADDING_ACTIVITY_FAILURE = 'ADDING_ACTIVITY_FAILURE';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const CLEAR_ACTIVITIES_SUCCESS = 'CLEAR_ACTIVITIES_SUCCESS';
export const CLEAR_ACTIVITIES_FAILURE = 'CLEAR_ACTIVITIES_FAILURE';
