export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const ADDING_ACTIVITY_SUCCESS = 'ADDING_ACTIVITY_SUCCESS';
export const ADDING_ACTIVITY_FAILURE = 'ADDING_ACTIVITY_FAILURE';
